name = "ma-project"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[vars]
DATABASE_HOST = "ep-damp-brook-a52lgtv9.us-east-2.aws.neon.tech"
DATABASE_USER = "neondb_owner"
DATABASE_PASSWORD = "ig89SnejZdwC"
DATABASE_NAME = "neondb"
DATABASE_TYPE = "pg"
FETCH_RAW_PRODUCT_DATASOURCE_URL = "https://02557f4d-8f03-405d-a4e7-7a6483d26a04.mock.pstmn.io/get"

